# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""span_attributes.py — Backward-compatible re-export module.

Re-exports centralized telemetry attribute constants from
``src.gateway.observability.attributes`` under historical SPAN_ATTR_* names.
"""

from __future__ import annotations

from src.gateway.observability.attributes import (
    AI_WEBHOOK_COOLDOWN_ACTIVE as SPAN_ATTR_AI_WEBHOOK_LANGFUSE_COOLDOWN_ACTIVE,
)
from src.gateway.observability.attributes import (
    AI_WEBHOOK_COOLDOWN_SECONDS_REMAINING as SPAN_ATTR_AI_WEBHOOK_LANGFUSE_COOLDOWN_SECONDS_REMAINING,
)
from src.gateway.observability.attributes import (
    AI_WEBHOOK_SCORE_NAME as SPAN_ATTR_AI_WEBHOOK_LANGFUSE_SCORE_NAME,
)
from src.gateway.observability.attributes import (
    AI_WEBHOOK_SCORE_VALUE as SPAN_ATTR_AI_WEBHOOK_LANGFUSE_SCORE_VALUE,
)
from src.gateway.observability.attributes import (
    AI_WEBHOOK_TRACE_ID as SPAN_ATTR_AI_WEBHOOK_LANGFUSE_TRACE_ID,
)
from src.gateway.observability.attributes import (
    OBSERVATION_INPUT as SPAN_ATTR_OBSERVATION_INPUT,
)
from src.gateway.observability.attributes import (
    OBSERVATION_METADATA_FALLBACK_REASON as SPAN_ATTR_OBSERVATION_METADATA_FALLBACK_REASON,
)
from src.gateway.observability.attributes import (
    OBSERVATION_METADATA_GOVERNANCE_STATE as SPAN_ATTR_OBSERVATION_METADATA_GOVERNANCE_STATE,
)
from src.gateway.observability.attributes import (
    OBSERVATION_METADATA_ISO_CONTROL as SPAN_ATTR_OBSERVATION_METADATA_ISO_CONTROL,
)
from src.gateway.observability.attributes import (
    OBSERVATION_METADATA_PREFIX as SPAN_ATTR_OBSERVATION_METADATA_PREFIX,
)
from src.gateway.observability.attributes import (
    OBSERVATION_METADATA_STPA_HAZARD as SPAN_ATTR_OBSERVATION_METADATA_STPA_HAZARD,
)
from src.gateway.observability.attributes import (
    OBSERVATION_MODEL_NAME as SPAN_ATTR_OBSERVATION_MODEL_NAME,
)
from src.gateway.observability.attributes import (
    OBSERVATION_NAME as SPAN_ATTR_OBSERVATION_NAME,
)
from src.gateway.observability.attributes import (
    OBSERVATION_OUTPUT as SPAN_ATTR_OBSERVATION_OUTPUT,
)
from src.gateway.observability.attributes import (
    OBSERVATION_TYPE as SPAN_ATTR_OBSERVATION_TYPE,
)
from src.gateway.observability.attributes import (
    SESSION_ID as SPAN_ATTR_SESSION_ID,
)
from src.gateway.observability.attributes import (
    SPAN_ATTR_CAGE_GOVERNANCE,
    SPAN_ATTR_CAGE_SEAL_ISSUED,
    SPAN_ATTR_CAGE_VERDICT,
    SPAN_ATTR_GEN_AI_OPERATION_NAME,
    SPAN_ATTR_GEN_AI_REQUEST_MODEL,
    SPAN_ATTR_GEN_AI_SYSTEM,
    SPAN_ATTR_GOVERNANCE_BLOCKED,
    SPAN_ATTR_GOVERNANCE_REASON,
    SPAN_ATTR_GOVERNANCE_STAGE,
    SPAN_ATTR_GOVERNANCE_TOOL,
    SPAN_ATTR_HITL_REGULATORY_CITATION,
    SPAN_ATTR_ISO42001_CONTROL_ID,
    SPAN_ATTR_MCP_TOOL_RESULT_LENGTH,
    SPAN_ATTR_OPA_POLICY_PATH,
    SPAN_ATTR_OPA_URL,
    SPAN_ATTR_THREAD_ID,
    WEBHOOK_THRESHOLD_BREACH,
    metadata,
    observation_metadata,
)
from src.gateway.observability.attributes import (
    TRACE_METADATA_CONSENSUS_DECISION as SPAN_ATTR_TRACE_METADATA_CONSENSUS_DECISION,
)
from src.gateway.observability.attributes import (
    TRACE_METADATA_CONSENSUS_VOTES as SPAN_ATTR_TRACE_METADATA_CONSENSUS_VOTES,
)
from src.gateway.observability.attributes import (
    TRACE_METADATA_CURRENT_NODE as SPAN_ATTR_TRACE_METADATA_CURRENT_NODE,
)
from src.gateway.observability.attributes import (
    TRACE_METADATA_GOVERNANCE_ACTION as SPAN_ATTR_TRACE_METADATA_GOVERNANCE_ACTION,
)
from src.gateway.observability.attributes import (
    TRACE_METADATA_GOVERNANCE_DECISION as SPAN_ATTR_TRACE_METADATA_GOVERNANCE_DECISION,
)
from src.gateway.observability.attributes import (
    TRACE_METADATA_GOVERNANCE_DENIAL_REASON as SPAN_ATTR_TRACE_METADATA_GOVERNANCE_DENIAL_REASON,
)
from src.gateway.observability.attributes import (
    TRACE_METADATA_GOVERNANCE_OPA_URL as SPAN_ATTR_TRACE_METADATA_GOVERNANCE_OPA_URL,
)
from src.gateway.observability.attributes import (
    TRACE_METADATA_GOVERNANCE_POLICY_INPUT_SIZE as SPAN_ATTR_TRACE_METADATA_GOVERNANCE_POLICY_INPUT_SIZE,
)
from src.gateway.observability.attributes import (
    TRACE_METADATA_GUARDRAIL_ACTION as SPAN_ATTR_TRACE_METADATA_GUARDRAIL_ACTION,
)
from src.gateway.observability.attributes import (
    TRACE_METADATA_GUARDRAIL_BLOCK_REASON as SPAN_ATTR_TRACE_METADATA_GUARDRAIL_BLOCK_REASON,
)
from src.gateway.observability.attributes import (
    TRACE_METADATA_GUARDRAIL_ID as SPAN_ATTR_TRACE_METADATA_GUARDRAIL_ID,
)
from src.gateway.observability.attributes import (
    TRACE_METADATA_GUARDRAILS_FRAMEWORK as SPAN_ATTR_TRACE_METADATA_GUARDRAILS_FRAMEWORK,
)
from src.gateway.observability.attributes import (
    TRACE_METADATA_GUARDRAILS_INPUT_LENGTH as SPAN_ATTR_TRACE_METADATA_GUARDRAILS_INPUT_LENGTH,
)
from src.gateway.observability.attributes import (
    TRACE_METADATA_GUARDRAILS_INTERVENED as SPAN_ATTR_TRACE_METADATA_GUARDRAILS_INTERVENED,
)
from src.gateway.observability.attributes import (
    TRACE_METADATA_GUARDRAILS_OUTCOME as SPAN_ATTR_TRACE_METADATA_GUARDRAIL_OUTCOME,
)
from src.gateway.observability.attributes import (
    TRACE_METADATA_ISO_CONTROL_ID as SPAN_ATTR_TRACE_METADATA_ISO_CONTROL_ID,
)
from src.gateway.observability.attributes import (
    TRACE_METADATA_ISO_CONTROL_ID_SECONDARY as SPAN_ATTR_TRACE_METADATA_ISO_CONTROL_ID_SECONDARY,
)
from src.gateway.observability.attributes import (
    TRACE_METADATA_ISO_REQUIREMENT as SPAN_ATTR_TRACE_METADATA_ISO_REQUIREMENT,
)
from src.gateway.observability.attributes import (
    TRACE_METADATA_ISO_REQUIREMENT_SECONDARY as SPAN_ATTR_TRACE_METADATA_ISO_REQUIREMENT_SECONDARY,
)
from src.gateway.observability.attributes import (
    TRACE_METADATA_LATENCY_CURRENCY_TAX as SPAN_ATTR_TRACE_METADATA_LATENCY_CURRENCY_TAX,
)
from src.gateway.observability.attributes import (
    TRACE_METADATA_MCP_SERVER as SPAN_ATTR_TRACE_METADATA_MCP_SERVER,
)
from src.gateway.observability.attributes import (
    TRACE_METADATA_POAM_REF as SPAN_ATTR_TRACE_METADATA_POAM_REF,
)
from src.gateway.observability.attributes import (
    TRACE_METADATA_PREFIX as SPAN_ATTR_TRACE_METADATA_PREFIX,
)
from src.gateway.observability.attributes import (
    TRACE_METADATA_RISK_VERDICT as SPAN_ATTR_TRACE_METADATA_RISK_VERDICT,
)
from src.gateway.observability.attributes import (
    TRACE_TAGS as SPAN_ATTR_TRACE_TAGS,
)

__all__ = [
    "SPAN_ATTR_AI_WEBHOOK_LANGFUSE_COOLDOWN_ACTIVE",
    "SPAN_ATTR_AI_WEBHOOK_LANGFUSE_COOLDOWN_SECONDS_REMAINING",
    "SPAN_ATTR_AI_WEBHOOK_LANGFUSE_SCORE_NAME",
    "SPAN_ATTR_AI_WEBHOOK_LANGFUSE_SCORE_VALUE",
    "SPAN_ATTR_AI_WEBHOOK_LANGFUSE_TRACE_ID",
    "SPAN_ATTR_CAGE_GOVERNANCE",
    "SPAN_ATTR_CAGE_SEAL_ISSUED",
    "SPAN_ATTR_CAGE_VERDICT",
    "SPAN_ATTR_GEN_AI_OPERATION_NAME",
    "SPAN_ATTR_GEN_AI_REQUEST_MODEL",
    "SPAN_ATTR_GEN_AI_SYSTEM",
    "SPAN_ATTR_GOVERNANCE_BLOCKED",
    "SPAN_ATTR_GOVERNANCE_REASON",
    "SPAN_ATTR_GOVERNANCE_STAGE",
    "SPAN_ATTR_GOVERNANCE_TOOL",
    "SPAN_ATTR_HITL_REGULATORY_CITATION",
    "SPAN_ATTR_ISO42001_CONTROL_ID",
    "SPAN_ATTR_MCP_TOOL_RESULT_LENGTH",
    "SPAN_ATTR_OBSERVATION_INPUT",
    "SPAN_ATTR_OBSERVATION_METADATA_FALLBACK_REASON",
    "SPAN_ATTR_OBSERVATION_METADATA_GOVERNANCE_STATE",
    "SPAN_ATTR_OBSERVATION_METADATA_ISO_CONTROL",
    "SPAN_ATTR_OBSERVATION_METADATA_PREFIX",
    "SPAN_ATTR_OBSERVATION_METADATA_STPA_HAZARD",
    "SPAN_ATTR_OBSERVATION_MODEL_NAME",
    "SPAN_ATTR_OBSERVATION_NAME",
    "SPAN_ATTR_OBSERVATION_OUTPUT",
    "SPAN_ATTR_OBSERVATION_TYPE",
    "SPAN_ATTR_OPA_POLICY_PATH",
    "SPAN_ATTR_OPA_URL",
    "SPAN_ATTR_SESSION_ID",
    "SPAN_ATTR_THREAD_ID",
    "SPAN_ATTR_TRACE_METADATA_CONSENSUS_DECISION",
    "SPAN_ATTR_TRACE_METADATA_CONSENSUS_VOTES",
    "SPAN_ATTR_TRACE_METADATA_CURRENT_NODE",
    "SPAN_ATTR_TRACE_METADATA_GOVERNANCE_ACTION",
    "SPAN_ATTR_TRACE_METADATA_GOVERNANCE_DECISION",
    "SPAN_ATTR_TRACE_METADATA_GOVERNANCE_DENIAL_REASON",
    "SPAN_ATTR_TRACE_METADATA_GOVERNANCE_OPA_URL",
    "SPAN_ATTR_TRACE_METADATA_GOVERNANCE_POLICY_INPUT_SIZE",
    "SPAN_ATTR_TRACE_METADATA_GUARDRAILS_FRAMEWORK",
    "SPAN_ATTR_TRACE_METADATA_GUARDRAILS_INPUT_LENGTH",
    "SPAN_ATTR_TRACE_METADATA_GUARDRAILS_INTERVENED",
    "SPAN_ATTR_TRACE_METADATA_GUARDRAIL_ACTION",
    "SPAN_ATTR_TRACE_METADATA_GUARDRAIL_BLOCK_REASON",
    "SPAN_ATTR_TRACE_METADATA_GUARDRAIL_ID",
    "SPAN_ATTR_TRACE_METADATA_GUARDRAIL_OUTCOME",
    "SPAN_ATTR_TRACE_METADATA_ISO_CONTROL_ID",
    "SPAN_ATTR_TRACE_METADATA_ISO_CONTROL_ID_SECONDARY",
    "SPAN_ATTR_TRACE_METADATA_ISO_REQUIREMENT",
    "SPAN_ATTR_TRACE_METADATA_ISO_REQUIREMENT_SECONDARY",
    "SPAN_ATTR_TRACE_METADATA_LATENCY_CURRENCY_TAX",
    "SPAN_ATTR_TRACE_METADATA_MCP_SERVER",
    "SPAN_ATTR_TRACE_METADATA_POAM_REF",
    "SPAN_ATTR_TRACE_METADATA_PREFIX",
    "SPAN_ATTR_TRACE_METADATA_RISK_VERDICT",
    "SPAN_ATTR_TRACE_TAGS",
    "WEBHOOK_THRESHOLD_BREACH",
    "metadata",
    "observation_metadata",
]
