# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Namespaced issuer: only Certificates in the linkerd namespace can use the
# mesh CA pool. No credentials Secret — the controller authenticates with
# GKE Workload Identity (KSA cert-manager/cage-cas-issuer).
apiVersion: cas-issuer.jetstack.io/v1beta1
kind: GoogleCASIssuer
metadata:
  name: cage-mesh-cas
  namespace: {{ .Release.Namespace }}
spec:
  project: {{ required "project is required" .Values.project | quote }}
  location: {{ required "location is required" .Values.location | quote }}
  caPoolId: {{ required "caPoolId is required" .Values.caPoolId | quote }}
