# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# =============================================================================
# AUTO-GENERATED by stpa_compiler — DO NOT EDIT
# Source: config/stpa_control_structure.yaml
# Generated: 2026-08-19T10:33:46.508693+00:00
# =============================================================================
# System: CAGE Financial Advisor v1.1.0
#
# Generated Python validator.  Extend GeneratedSTPAValidator in your
# STPAValidator subclass or use it directly as a drop-in replacement.
#
# All threshold references are resolved from the THRESHOLDS singleton
# (config/governance_thresholds.json).

from __future__ import annotations

import logging
import math
from typing import Any

from src.gateway.governance.schemas.thresholds import THRESHOLDS

logger = logging.getLogger("Gateway.Governance.GeneratedSTPAValidator")


class GeneratedSTPAValidator:
    """
    Auto-generated STPA validator.

    Checks all UCAs with enforcement=[python] or enforcement=[all] that were
    defined in config/stpa_control_structure.yaml.

    Do NOT edit this file; re-run the compiler instead:
        python -m src.gateway.governance.stpa_compiler compile
    """

    def validate(self, action_name: str, params: dict[str, Any]) -> list[str]:
        """Public entry-point — delegates to validate_generated().

        Call-sites that previously used STPAValidator.validate() can use this
        method directly on GeneratedSTPAValidator without going through the
        deprecated shim in stpa_validator.py.
        """
        return self.validate_generated(action_name, params)

    def validate_generated(self, action_name: str, params: dict[str, Any]) -> list[str]:
        """Run all generated UCA checks. Returns list of violation strings."""
        violations: list[str] = []
        _v = self._check_uca_1(action_name, params)
        if _v:
            violations.append(_v)
        _v = self._check_uca_2(action_name, params)
        if _v:
            violations.append(_v)
        _v = self._check_uca_5(action_name, params)
        if _v:
            violations.append(_v)
        _v = self._check_uca_6(action_name, params)
        if _v:
            violations.append(_v)
        _v = self._check_uca_8(action_name, params)
        if _v:
            violations.append(_v)
        _v = self._check_uca_9(action_name, params)
        if _v:
            violations.append(_v)
        return violations

    def _check_uca_1(self, action_name: str, params: dict) -> str | None:
        """UCA-1: Agent executes write operation without a signed approval token."""
        try:
            if action_name != "write_db":
                return None
            if params.get("approval_token") is None:
                return "STPA Violation UCA-1: Agent executes write operation without a signed approval token."
            return None
        except Exception as exc:
            logger.error("Error evaluating UCA-1: %s", exc)
            return f"STPA Violation UCA-1: Evaluation error — failing closed ({exc})."

    def _check_uca_2(self, action_name: str, params: dict) -> str | None:
        """UCA-2: Agent executes trade with stale market data (latency > threshold)."""
        try:
            if action_name != "execute_trade":
                return None
            threshold = THRESHOLDS.stpa.max_latency_ms
            val = params.get("latency_ms")
            if val is None:
                logger.warning("UCA-2: missing param `latency_ms` — failing closed.")
                return "STPA Violation UCA-2: Missing required param `latency_ms`."
            numeric = float(val)
            if not math.isfinite(numeric):
                logger.warning("UCA-2: non-finite param `latency_ms` — failing closed.")
                return "STPA Violation UCA-2: Non-finite param `latency_ms`."
            if numeric > threshold:
                return f"STPA Violation UCA-2: Agent executes trade with stale market data (latency > threshold). ({numeric:.4f} > {threshold})"
            return None
        except Exception as exc:
            logger.error("Error evaluating UCA-2: %s", exc)
            return f"STPA Violation UCA-2: Evaluation error — failing closed ({exc})."

    def _check_uca_5(self, action_name: str, params: dict) -> str | None:
        """UCA-5: Agent executes buy order when daily drawdown exceeds limit."""
        try:
            if action_name != "execute_trade":
                return None
            threshold = THRESHOLDS.stpa.uca5_drawdown_threshold_pct
            val = params.get("drawdown")
            if val is None:
                logger.warning("UCA-5: missing param `drawdown` — failing closed.")
                return "STPA Violation UCA-5: Missing required param `drawdown`."
            numeric = float(val)
            if not math.isfinite(numeric):
                logger.warning("UCA-5: non-finite param `drawdown` — failing closed.")
                return "STPA Violation UCA-5: Non-finite param `drawdown`."
            if numeric > threshold:
                return f"STPA Violation UCA-5: Agent executes buy order when daily drawdown exceeds limit. ({numeric:.4f} > {threshold})"
            return None
        except Exception as exc:
            logger.error("Error evaluating UCA-5: %s", exc)
            return f"STPA Violation UCA-5: Evaluation error — failing closed ({exc})."

    def _check_uca_6(self, action_name: str, params: dict) -> str | None:
        """UCA-6: Agent submits market order exceeding allowable fraction of daily volume."""
        try:
            if action_name != "execute_trade":
                return None
            # Composite condition: order_size > threshold_ref(stpa.uca6_max_order_volume_fraction) * daily_vol
            # Implement custom logic here.
            pass
            return None
        except Exception as exc:
            logger.error("Error evaluating UCA-6: %s", exc)
            return f"STPA Violation UCA-6: Evaluation error — failing closed ({exc})."

    def _check_uca_8(self, action_name: str, params: dict) -> str | None:
        """UCA-8: Agent executes trade before risk assessment is complete."""
        try:
            if action_name != "execute_trade":
                return None
            if params.get("risk_assessed") is False:
                return "STPA Violation UCA-8: Agent executes trade before risk assessment is complete."
            return None
        except Exception as exc:
            logger.error("Error evaluating UCA-8: %s", exc)
            return f"STPA Violation UCA-8: Evaluation error — failing closed ({exc})."

    def _check_uca_9(self, action_name: str, params: dict) -> str | None:
        """UCA-9: Agent executes trade with compliance check bypassed."""
        try:
            if action_name != "execute_trade":
                return None
            if params.get("compliance_checked") is False:
                return "STPA Violation UCA-9: Agent executes trade with compliance check bypassed."
            return None
        except Exception as exc:
            logger.error("Error evaluating UCA-9: %s", exc)
            return f"STPA Violation UCA-9: Evaluation error — failing closed ({exc})."
