# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# =============================================================================
# AUTO-GENERATED by stpa_compiler — DO NOT EDIT
# Source: config/stpa_control_structure.yaml
# Generated: 2026-10-01T01:04:43.526966+00:00
# =============================================================================

# System: CAGE Financial Advisor v1.1.0
#
# This policy enforces STPA Unsafe Control Actions (UCAs) identified in
# config/stpa_control_structure.yaml.  It is loaded by OPA alongside
# trade_governance.rego (which owns RBAC rules).
#
package stpa.generated

import rego.v1

# Fail-closed default: any action not explicitly allowed is denied.
default stpa_allow = false

# ---------------------------------------------------------------------------
# STPA safety constraints
# ---------------------------------------------------------------------------

# --- Action: write_db ---
# UCA-1: Agent executes write operation without a signed approval token.
stpa_violation_uca_1 := msg if {
    input.action == "write_db"
    not input.approval_token
    msg := "UCA-1: write_db requires a signed approval_token."
}

# --- Action: prompt_injection_check ---
# UCA-7: Adversarial prompt injection score exceeds detection threshold.
stpa_violation_uca_7 := msg if {
    input.action == "prompt_injection_check"
    input.semantic_score > 0.85
    msg := "UCA-7: Prompt injection detected — governance violation."
}

# ---------------------------------------------------------------------------
# Aggregate: deny if any STPA violation fires
# ---------------------------------------------------------------------------

stpa_violations contains msg if msg := stpa_violation_uca_1
stpa_violations contains msg if msg := stpa_violation_uca_7

stpa_allow if {
    count(stpa_violations) == 0
}
