# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# =============================================================================
# AUTO-GENERATED by stpa_compiler — DO NOT EDIT
# Source: config/stpa_control_structure.yaml
# Generated: 2026-07-07T22:46:55.012117+00:00
# =============================================================================

# System: CAGE Financial Advisor v1.1.0
#
# This policy enforces STPA Unsafe Control Actions (UCAs) identified in
# config/stpa_control_structure.yaml.  It is loaded by OPA alongside
# trade_governance.rego (which owns RBAC rules).
#
package stpa.generated

import rego.v1

# Fail-closed default: any action not explicitly allowed is denied.
default stpa_allow = false

# ---------------------------------------------------------------------------
# STPA safety constraints
# ---------------------------------------------------------------------------

# --- Action: write_db ---
# UCA-1: Agent executes write operation without a signed approval token.
stpa_violation_uca_1 := msg if {
    input.action == "write_db"
    not input.approval_token
    msg := "UCA-1: write_db requires a signed approval_token."
}

# --- Action: execute_trade ---
# UCA-2: Agent executes trade with stale market data (latency > threshold).
stpa_violation_uca_2 := msg if {
    input.action == "execute_trade"
    input.latency_ms > input._thresholds.stpa_max_latency_ms  # threshold from governance_thresholds.json:stpa.max_latency_ms
    msg := "UCA-2: Market data latency exceeds maximum allowable threshold."
}

# UCA-5: Agent executes buy order when daily drawdown exceeds limit.
stpa_violation_uca_5 := msg if {
    input.action == "execute_trade"
    input.drawdown > input._thresholds.stpa_uca5_drawdown_threshold_pct  # threshold from governance_thresholds.json:stpa.uca5_drawdown_threshold_pct
    msg := "UCA-5: Drawdown exceeds maximum threshold — trade blocked."
}

# UCA-6: Agent submits market order exceeding allowable fraction of daily volume.
stpa_violation_uca_6 := msg if {
    input.action == "execute_trade"
    # composite: order_size > threshold_ref(stpa.uca6_max_order_volume_fraction) * daily_vol
    # NOTE: complex composite condition — enforce via Python validator.
    false  # placeholder: evaluated in STPAValidator
    msg := "UCA-6: Order size exceeds maximum daily volume fraction — slippage risk."
}

# --- Action: prompt_injection_check ---
# UCA-7: Adversarial prompt injection score exceeds detection threshold.
stpa_violation_uca_7 := msg if {
    input.action == "prompt_injection_check"
    input.semantic_score > 0.85
    msg := "UCA-7: Prompt injection detected — governance violation."
}

# ---------------------------------------------------------------------------
# Aggregate: deny if any STPA violation fires
# ---------------------------------------------------------------------------

stpa_violations contains msg if msg := stpa_violation_uca_1
stpa_violations contains msg if msg := stpa_violation_uca_2
stpa_violations contains msg if msg := stpa_violation_uca_5
stpa_violations contains msg if msg := stpa_violation_uca_6
stpa_violations contains msg if msg := stpa_violation_uca_7

stpa_allow if {
    count(stpa_violations) == 0
}

# ---------------------------------------------------------------------------
# RBAC rules (compiled from stpa_control_structure.yaml rbac_rules)
# ---------------------------------------------------------------------------

# Role: junior
rbac_allow_junior_trade if {
    input.action == "execute_trade"
    lower(input.trader_role) == "junior"
    input.amount <= 5000
    input.currency != "BTC"
}

rbac_review_junior_trade if {
    input.action == "execute_trade"
    lower(input.trader_role) == "junior"
    input.amount > 5000
    input.amount <= 10000
    input.currency != "BTC"
}

# Role: senior
rbac_allow_senior_trade if {
    input.action == "execute_trade"
    lower(input.trader_role) == "senior"
    input.amount <= 500000
    input.currency != "BTC"
}

rbac_review_senior_trade if {
    input.action == "execute_trade"
    lower(input.trader_role) == "senior"
    input.amount > 500000
    input.amount <= 1000000
    input.currency != "BTC"
}
