# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from typing import Any

# AUTOMATICALLY GENERATED BY GOVERNANCE TRANSPILER


def check_slippage_risk(context: dict[str, Any] = {}, event: dict[str, Any] = {}) -> bool:
    '''
    Enforces H-Slippage: Blocks market orders exceeding 0.01 of daily volume.
    Condition: order_type==MARKET
    '''
    order_type = context.get("order_type", "MARKET")
    order_size = float(context.get("order_size", 0))
    daily_vol = float(context.get("daily_volume", 1000000))

    if order_type == "MARKET" and order_size > (daily_vol * 0.01):
        # UCA Detected: Wrong Order
        return False

    return True


def check_drawdown_limit(context: dict[str, Any] = {}, event: dict[str, Any] = {}) -> bool:
    '''
    Enforces H-Drawdown: Blocks buy orders if drawdown > 4.5%.
    '''
    current_drawdown = float(context.get("drawdown_pct", 0))
    if current_drawdown > 4.5:
        return False
    return True
