# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""POAM-2026-080: the mesh half of the gateway's ingress check.

The gateway admits a caller in two places: the Linkerd proxy
(Server/HTTPRoute/AuthorizationPolicy) and the app
(``WorkloadIdentityMiddleware``). These tests keep the two layers, the raw
manifests and the Terraform path describing the same policy:

* the open paths are identical everywhere;
* everything else is gated to the advisor's mesh identity only;
* Linkerd policy objects use API versions that Linkerd edge-26.9.3 serves;
* no CA private key is generated by Terraform (it would sit in state);
* no ingress HMAC secret is wired into any deployment path.
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

import pytest
import yaml

from src.gateway.server.workload_identity import (
    _LINKERD_IDENTITY,
    OPEN_EXACT_PATHS,
)

pytestmark = [pytest.mark.unit, pytest.mark.local]

_REPO = Path(__file__).resolve().parents[1]
_RAW_POLICY = _REPO / "deployment" / "k8s" / "linkerd-mtls-policy.yaml"
_CHART = _REPO / "infra" / "modules" / "gateway" / "mesh-policy"
_MESH_MODULE = _REPO / "infra" / "modules" / "service_mesh"
_GKE_MAIN = _REPO / "infra" / "targets" / "gcp-gke" / "main.tf"
_GATEWAY_MODULE = _REPO / "infra" / "modules" / "gateway" / "main.tf"
_RAW_GATEWAYS = [
    _REPO / "deployment" / "k8s" / "gateway.yaml",
    _REPO / "deployment" / "k8s" / "gateway.yaml.tpl",
]

ADVISOR_IDENTITY = "cage-advisor-sa.governance-stack.serviceaccount.identity.linkerd.cluster.local"
GATEWAY_IDENTITY = "cage-gateway-sa.governance-stack.serviceaccount.identity.linkerd.cluster.local"

# Served versions in Linkerd edge-26.9.3 (linkerd-crds chart).
_SERVED = {
    "AuthorizationPolicy": {"v1alpha1"},
    "MeshTLSAuthentication": {"v1alpha1"},
    "NetworkAuthentication": {"v1alpha1"},
    "Server": {"v1alpha1", "v1beta1", "v1beta2", "v1beta3"},
    "HTTPRoute": {"v1alpha1", "v1beta1", "v1beta2", "v1beta3"},
}


# ---------------------------------------------------------------------------
# Helpers (also exercised against planted violations below)
# ---------------------------------------------------------------------------


def _docs(path: Path) -> list[dict]:
    return [d for d in yaml.safe_load_all(path.read_text()) if d]


def _by(docs: list[dict], kind: str, name: str) -> dict:
    matches = [d for d in docs if d["kind"] == kind and d["metadata"]["name"] == name]
    assert len(matches) == 1, f"expected one {kind}/{name}, found {len(matches)}"
    return matches[0]


def open_route_paths(route: dict) -> set[str]:
    """Exact paths of an open HTTPRoute. Only exact paths may be open: a
    prefix (of any method) would open a route family, so it is rejected."""
    exact: set[str] = set()
    for rule in route["spec"]["rules"]:
        for match in rule["matches"]:
            path = match["path"]
            if path["type"] == "Exact":
                exact.add(path["value"])
            else:
                raise AssertionError(f"open route may only hold Exact paths: {match}")
    return exact


def gateway_policy_violations(docs: list[dict]) -> list[str]:
    """Every way the raw gateway policy can drift from the app's policy."""
    problems: list[str] = []
    exact = open_route_paths(_by(docs, "HTTPRoute", "gateway-open"))
    if exact != set(OPEN_EXACT_PATHS):
        problems.append(f"open exact paths {sorted(exact)} != app {sorted(OPEN_EXACT_PATHS)}")

    gated = _by(docs, "HTTPRoute", "gateway-gated")
    matches = [m for r in gated["spec"]["rules"] for m in r["matches"]]
    if matches != [{"path": {"type": "PathPrefix", "value": "/"}}]:
        problems.append(f"gated route must be exactly PathPrefix '/', got {matches}")

    policy = _by(docs, "AuthorizationPolicy", "gateway-gated")
    if policy["spec"]["targetRef"] != {"group": "policy.linkerd.io", "kind": "HTTPRoute", "name": "gateway-gated"}:
        problems.append(f"gateway-gated policy targets {policy['spec']['targetRef']}")
    refs = policy["spec"]["requiredAuthenticationRefs"]
    if [r["kind"] for r in refs] != ["MeshTLSAuthentication"]:
        problems.append(f"gated route must require mesh identity only, got {refs}")
    else:
        identities = set(_by(docs, "MeshTLSAuthentication", refs[0]["name"])["spec"]["identities"])
        if identities != {ADVISOR_IDENTITY}:
            problems.append(f"gated identities {sorted(identities)} != {{advisor}}")
    return problems


def served_version_violations(text: str) -> list[str]:
    """Linkerd policy objects whose apiVersion edge-26.9.3 does not serve."""
    out = []
    for version, kind in re.findall(r"apiVersion:\s*policy\.linkerd\.io/(\w+)\s*\nkind:\s*(\w+)", text):
        if kind in _SERVED and version not in _SERVED[kind]:
            out.append(f"{kind} policy.linkerd.io/{version}")
    return out


# ---------------------------------------------------------------------------
# Raw manifests
# ---------------------------------------------------------------------------


def test_raw_gateway_policy_matches_app_policy() -> None:
    assert gateway_policy_violations(_docs(_RAW_POLICY)) == []


def test_raw_policy_does_not_trust_the_gateway_itself() -> None:
    docs = _docs(_RAW_POLICY)
    authn = _by(docs, "MeshTLSAuthentication", "gateway-trusted-clients")
    assert GATEWAY_IDENTITY not in authn["spec"]["identities"]


def test_open_route_allows_any_network_only_for_open_paths() -> None:
    docs = _docs(_RAW_POLICY)
    policy = _by(docs, "AuthorizationPolicy", "gateway-open")
    assert policy["spec"]["targetRef"]["name"] == "gateway-open"
    assert [r["kind"] for r in policy["spec"]["requiredAuthenticationRefs"]] == ["NetworkAuthentication"]
    network_policies = [
        d for d in docs
        if d["kind"] == "AuthorizationPolicy"
        and any(r["kind"] == "NetworkAuthentication" for r in d["spec"]["requiredAuthenticationRefs"])
    ]
    assert [p["metadata"]["name"] for p in network_policies] == ["gateway-open"]


@pytest.mark.parametrize("path", _RAW_GATEWAYS, ids=lambda p: p.name)
def test_raw_gateway_trusts_exactly_the_policy_identities(path: Path) -> None:
    text = path.read_text()
    values = re.findall(r"- name: CAGE_TRUSTED_CLIENT_IDENTITIES\n(?:\s*#.*\n)*\s*value: \"([^\"]+)\"", text)
    assert values == [ADVISOR_IDENTITY]
    assert all(_LINKERD_IDENTITY.match(v) for v in values[0].split(","))


@pytest.mark.parametrize("path", _RAW_GATEWAYS, ids=lambda p: p.name)
def test_raw_gateway_has_no_ingress_hmac_secret(path: Path) -> None:
    text = path.read_text()
    assert "CAGE_ROUTING_SEAL_SECRET" not in text
    assert "cage-routing-seal" not in text


def test_all_linkerd_objects_use_served_api_versions() -> None:
    sources = list((_REPO / "deployment").rglob("*.yaml")) + list((_REPO / "infra").rglob("templates/*.yaml"))
    bad = {str(p.relative_to(_REPO)): v for p in sources if (v := served_version_violations(p.read_text()))}
    assert bad == {}


# ---------------------------------------------------------------------------
# Terraform path
# ---------------------------------------------------------------------------


def test_chart_open_paths_match_app_policy() -> None:
    values = yaml.safe_load((_CHART / "values.yaml").read_text())
    assert set(values["openExactPaths"]) == set(OPEN_EXACT_PATHS)
    assert "openGetPrefixes" not in values, "no prefix may be open; only exact paths"
    assert values["trustedIdentities"] == []


def test_chart_gates_everything_else_to_mesh_identities() -> None:
    template = (_CHART / "templates" / "policy.yaml").read_text()
    gated = template[template.index("name: gateway-gated"):]
    assert re.search(r"type: PathPrefix\s*\n\s*value: /\s*\n", gated)
    # The gated AuthorizationPolicy only exists when identities are given, so
    # an empty list leaves the catch-all route with no policy: deny all.
    auth = template[template.index("{{- if .Values.trustedIdentities }}"):]
    assert "kind: MeshTLSAuthentication" in auth
    assert "name: gateway-gated" in auth
    assert "NetworkAuthentication" not in auth


def test_gateway_module_wires_identities_not_hmac() -> None:
    text = _GATEWAY_MODULE.read_text()
    assert 'name  = "CAGE_TRUSTED_CLIENT_IDENTITIES"' in text
    assert 'join(",", var.trusted_client_identities)' in text
    assert "CAGE_ROUTING_SEAL_SECRET" not in text
    assert 'resource "helm_release" "mesh_policy"' in text


def test_gke_target_trusts_only_the_advisor_and_meshes_the_namespace() -> None:
    text = _GKE_MAIN.read_text()
    block = re.search(r"trusted_client_identities = \[(.*?)\]", text, re.S)
    assert block is not None
    entries = [e.strip().rstrip(",") for e in block.group(1).splitlines() if e.strip() and not e.strip().startswith("#")]
    assert entries == ['"${local.ksa_advisor}.${module.namespace.name}.${module.service_mesh.identity_suffix}"']
    assert '"linkerd.io/inject" = "enabled"' in text
    assert "routing_seal_secret" not in text


def test_no_ca_private_key_is_generated_by_terraform() -> None:
    """A tls_private_key would put the CA key in Terraform state."""
    offenders = [
        str(p.relative_to(_REPO))
        for p in (_REPO / "infra").rglob("*.tf")
        if re.search(r'resource\s+"tls_(private_key|self_signed_cert|locally_signed_cert)"', p.read_text())
    ]
    assert offenders == []


def test_mesh_trust_anchor_lives_in_cas() -> None:
    text = (_MESH_MODULE / "main.tf").read_text()
    assert 'resource "google_privateca_certificate_authority" "mesh_root"' in text
    assert 'type                     = "SELF_SIGNED"' in text
    assert "identityTrustAnchorsPEM = google_privateca_certificate_authority.mesh_root.pem_ca_certificates[0]" in text
    assert 'issuer     = { scheme = "kubernetes.io/tls" }' in text
    # The CAS issuer identity may request certificates, nothing more.
    assert 'role    = "roles/privateca.certificateRequester"' in text
    assert "roles/privateca.admin" not in text


def test_no_ingress_hmac_secret_in_infra() -> None:
    tracked = subprocess.run(
        ["git", "ls-files", "-z", "--cached", "--others", "--exclude-standard", "--", "infra"],
        cwd=_REPO, check=True, capture_output=True, text=True,
    ).stdout.split("\0")
    offenders = [
        f for f in tracked
        if f and (_REPO / f).is_file()
        and re.search(r"routing_seal_secret|CAGE_ROUTING_SEAL_SECRET", (_REPO / f).read_text(errors="ignore"))
    ]
    assert offenders == []


# ---------------------------------------------------------------------------
# The checks above must actually catch drift (fail-closed observation)
# ---------------------------------------------------------------------------


def _mutated(mutate) -> list[dict]:
    docs = _docs(_RAW_POLICY)
    mutate(docs)
    return docs


def test_detects_an_extra_open_path() -> None:
    def add_open(docs):
        _by(docs, "HTTPRoute", "gateway-open")["spec"]["rules"][0]["matches"].append(
            {"path": {"type": "Exact", "value": "/mcp/sse"}}
        )
    assert any("open exact paths" in p for p in gateway_policy_violations(_mutated(add_open)))


@pytest.mark.parametrize("method", [None, "GET"])
def test_detects_any_open_prefix(method: str | None) -> None:
    """A PathPrefix on the open route, with or without a method, is refused:
    the gateway opens exact paths only."""
    def add_prefix(docs):
        match = {"path": {"type": "PathPrefix", "value": "/governance/"}}
        if method:
            match["method"] = method
        _by(docs, "HTTPRoute", "gateway-open")["spec"]["rules"][0]["matches"].append(match)
    with pytest.raises(AssertionError, match="open route may only hold"):
        gateway_policy_violations(_mutated(add_prefix))


def test_detects_a_narrowed_gated_route() -> None:
    def narrow(docs):
        _by(docs, "HTTPRoute", "gateway-gated")["spec"]["rules"][0]["matches"] = [
            {"path": {"type": "PathPrefix", "value": "/governance/"}}
        ]
    assert any("gated route must be exactly" in p for p in gateway_policy_violations(_mutated(narrow)))


def test_detects_an_extra_trusted_identity() -> None:
    def widen(docs):
        _by(docs, "MeshTLSAuthentication", "gateway-trusted-clients")["spec"]["identities"].append(GATEWAY_IDENTITY)
    assert any("gated identities" in p for p in gateway_policy_violations(_mutated(widen)))


def test_detects_network_auth_on_the_gated_route() -> None:
    def open_up(docs):
        _by(docs, "AuthorizationPolicy", "gateway-gated")["spec"]["requiredAuthenticationRefs"] = [
            {"group": "policy.linkerd.io", "kind": "NetworkAuthentication", "name": "gateway-any-network"}
        ]
    assert any("mesh identity only" in p for p in gateway_policy_violations(_mutated(open_up)))


def test_detects_an_unserved_authorization_policy_version() -> None:
    planted = "apiVersion: policy.linkerd.io/v1beta2\nkind: AuthorizationPolicy\n"
    assert served_version_violations(planted) == ["AuthorizationPolicy policy.linkerd.io/v1beta2"]
