# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Data models for CAGE PolicyProvider plugin in OpenShell."""

from __future__ import annotations

from typing import Any
from pydantic import BaseModel, Field


class PolicyProposal(BaseModel):
    """Proposal generated by OpenShell supervisor before executing an agent action."""

    sandbox_id: str = Field(min_length=1, max_length=128)
    thread_id: str = Field(min_length=1, max_length=128)
    action: str = Field(min_length=1, max_length=128)
    requested_endpoint: str | None = Field(default=None, max_length=512)
    requested_http_verb: str = Field(default="POST", max_length=16)
    operator_urn: str = Field(default="urn:cage:agent:sandbox")
    params: dict[str, Any] = Field(default_factory=dict)
    correlation_id: str | None = None


class PolicyEvaluationOutcome(BaseModel):
    """Normalized evaluation result returned to OpenShell supervisor."""

    allowed: bool
    deferred: bool
    rejected: bool
    decision: str  # ALLOW, REQUIRE_APPROVAL, DEFER, NARROW, DENY
    defer_id: str | None = None
    routing_seal: str | None = None
    rejection_reason: str = ""
    violations: list[str] = Field(default_factory=list)
    quarantine_triggered: bool = False
    metadata: dict[str, Any] = Field(default_factory=dict)
