# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ─── Service mesh: Linkerd with a Google CAS-backed trust anchor ─────────────
#
# POAM-2026-080. The gateway authenticates callers by mTLS workload identity
# (l5d-client-id). This module provides that identity:
#
#   Google CAS root CA (HSM key, never leaves CAS)          ← trust anchor
#     └─ Linkerd identity issuer (cert-manager, 48h, CSR)   ← linkerd-identity-issuer Secret
#          └─ per-pod proxy certificates (24h)              ← Linkerd identity controller
#
# No CA private key exists in Terraform state or in any file: the root key is
# generated inside CAS, and the issuer key is generated by cert-manager inside
# the cluster and only its CSR is sent to CAS.
#
# Install order: cert-manager → CAS issuer → Linkerd CRDs (+ CNI) → issuer
# certificate → Linkerd control plane.

terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 6.43"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.23"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.11"
    }
  }
}

locals {
  # Pinned chart versions. Linkerd edge-26.9.3 ships its charts as 2026.9.3.
  linkerd_chart_version    = "2026.9.3"
  linkerd_repository       = "https://helm.linkerd.io/edge"
  cert_manager_version     = "v1.21.2"
  cas_issuer_chart_version = "v0.13.0"
  cert_manager_namespace   = "cert-manager"
  linkerd_namespace        = "linkerd"
  linkerd_cni_namespace    = "linkerd-cni"
  cas_issuer_ksa           = "cage-cas-issuer"
  identity_issuer_dns_name = "identity.${local.linkerd_namespace}.${var.cluster_domain}"
  ca_pool_id               = "cage-mesh-${var.environment}"
}

# ─── Certificate Authority Service ────────────────────────────────────────────

resource "google_project_service" "privateca" {
  project            = var.project_id
  service            = "privateca.googleapis.com"
  disable_on_destroy = false
}

# One pool, used only for the Linkerd identity issuer. Its issuance policy is
# the security boundary for the cert-manager identity: it can only obtain a
# P-256, path-length-0 CA certificate named for the Linkerd identity service,
# valid for at most 7 days.
resource "google_privateca_ca_pool" "mesh" {
  name     = local.ca_pool_id
  project  = var.project_id
  location = var.region
  # Enterprise tier: issued certificates are listed and revocable, so a leaked
  # issuer certificate can be revoked and audited.
  tier = "ENTERPRISE"

  publishing_options {
    publish_ca_cert = false
    publish_crl     = false
  }

  issuance_policy {
    maximum_lifetime = "604800s"

    allowed_key_types {
      elliptic_curve {
        signature_algorithm = "ECDSA_P256"
      }
    }

    allowed_issuance_modes {
      allow_csr_based_issuance    = true
      allow_config_based_issuance = false
    }

    identity_constraints {
      allow_subject_passthrough           = true
      allow_subject_alt_names_passthrough = true
      cel_expression {
        title       = "linkerd-identity-issuer-only"
        description = "Only the Linkerd identity issuer name may be certified."
        expression  = "subject.common_name == '${local.identity_issuer_dns_name}' && subject_alt_names.all(san, san.type == DNS && san.value == '${local.identity_issuer_dns_name}')"
      }
    }

    baseline_values {
      ca_options {
        is_ca                       = true
        zero_max_issuer_path_length = true
      }
      key_usage {
        base_key_usage {
          cert_sign         = true
          crl_sign          = true
          digital_signature = true
        }
        extended_key_usage {
          server_auth = true
          client_auth = true
        }
      }
    }
  }

  depends_on = [google_project_service.privateca]
}

# The mesh trust anchor. CAS generates and keeps the key in a Google-managed
# HSM; only the public certificate leaves CAS (identityTrustAnchorsPEM below).
resource "google_privateca_certificate_authority" "mesh_root" {
  pool                     = google_privateca_ca_pool.mesh.name
  certificate_authority_id = "cage-mesh-root-${var.environment}"
  project                  = var.project_id
  location                 = var.region
  type                     = "SELF_SIGNED"
  lifetime                 = "315360000s" # 10 years

  config {
    subject_config {
      subject {
        organization = "CAGE"
        common_name  = "cage-mesh-root-${var.environment}"
      }
    }
    x509_config {
      ca_options {
        is_ca                  = true
        max_issuer_path_length = 1
      }
      key_usage {
        base_key_usage {
          cert_sign = true
          crl_sign  = true
        }
        extended_key_usage {}
      }
    }
  }

  key_spec {
    algorithm = "EC_P256_SHA256"
  }
}

# ─── cert-manager issuer identity ─────────────────────────────────────────────
# The CAS issuer controller runs as KSA cert-manager/cage-cas-issuer, bound 1:1
# to this GSA, which may only request certificates from the mesh pool.

resource "google_service_account" "cas_issuer" {
  account_id   = "cage-cas-issuer"
  project      = var.project_id
  display_name = "CAGE mesh CAS issuer"
  description  = "cert-manager google-cas-issuer. Requests the Linkerd identity issuer certificate from the mesh CA pool only (POAM-2026-080)."
}

resource "google_privateca_ca_pool_iam_member" "cas_issuer_requester" {
  ca_pool = google_privateca_ca_pool.mesh.id
  role    = "roles/privateca.certificateRequester"
  member  = "serviceAccount:${google_service_account.cas_issuer.email}"
}

resource "google_service_account_iam_binding" "cas_issuer_workload_identity" {
  service_account_id = google_service_account.cas_issuer.name
  role               = "roles/iam.workloadIdentityUser"
  members = [
    "serviceAccount:${var.project_id}.svc.id.goog[${local.cert_manager_namespace}/${local.cas_issuer_ksa}]",
  ]
}

# ─── Private-cluster firewall for admission webhooks ─────────────────────────
# A private GKE control plane reaches nodes only on 443/10250 by default. The
# Linkerd proxy injector and SP validator listen on 8443 and the policy
# validator on 9443; without this rule injection silently never happens.

resource "google_compute_firewall" "mesh_webhooks" {
  name          = "cage-mesh-webhooks-${var.environment}"
  project       = var.project_id
  network       = var.network
  direction     = "INGRESS"
  source_ranges = [var.master_ipv4_cidr_block]
  description   = "GKE control plane to Linkerd admission webhooks (POAM-2026-080)."

  allow {
    protocol = "tcp"
    ports    = ["8443", "9443"]
  }
}

# ─── cert-manager and the Google CAS issuer ───────────────────────────────────

resource "helm_release" "cert_manager" {
  name             = "cert-manager"
  repository       = "https://charts.jetstack.io"
  chart            = "cert-manager"
  version          = local.cert_manager_version
  namespace        = local.cert_manager_namespace
  create_namespace = true
  wait             = true

  values = [yamlencode({
    crds = { enabled = true, keep = true }
  })]
}

resource "helm_release" "cas_issuer" {
  name       = "cert-manager-google-cas-issuer"
  repository = "oci://quay.io/jetstack/charts"
  chart      = "cert-manager-google-cas-issuer"
  version    = local.cas_issuer_chart_version
  namespace  = local.cert_manager_namespace
  wait       = true

  values = [yamlencode({
    # The chart names its ServiceAccount after nameOverride.
    nameOverride = local.cas_issuer_ksa
    serviceAccount = {
      annotations = {
        "iam.gke.io/gcp-service-account" = google_service_account.cas_issuer.email
      }
    }
  })]

  depends_on = [
    helm_release.cert_manager,
    google_service_account_iam_binding.cas_issuer_workload_identity,
    google_privateca_ca_pool_iam_member.cas_issuer_requester,
  ]
}

# ─── Linkerd ─────────────────────────────────────────────────────────────────

resource "kubernetes_namespace" "linkerd" {
  metadata {
    name = local.linkerd_namespace
    labels = {
      "linkerd.io/is-control-plane"          = "true"
      "linkerd.io/control-plane-ns"          = local.linkerd_namespace
      "config.linkerd.io/admission-webhooks" = "disabled"
    }
    annotations = {
      "linkerd.io/inject" = "disabled"
    }
  }
}

resource "helm_release" "linkerd_crds" {
  name       = "linkerd-crds"
  repository = local.linkerd_repository
  chart      = "linkerd-crds"
  version    = local.linkerd_chart_version
  namespace  = kubernetes_namespace.linkerd.metadata[0].name
  wait       = true
}

resource "kubernetes_namespace" "linkerd_cni" {
  count = var.enable_cni ? 1 : 0

  metadata {
    name = local.linkerd_cni_namespace
    labels = {
      "config.linkerd.io/admission-webhooks" = "disabled"
      "linkerd.io/cni-resource"              = "true"
      # The CNI DaemonSet writes to the node's CNI directories (hostPath).
      "pod-security.kubernetes.io/enforce" = "privileged"
    }
  }
}

resource "helm_release" "linkerd_cni" {
  count = var.enable_cni ? 1 : 0

  name       = "linkerd2-cni"
  repository = local.linkerd_repository
  chart      = "linkerd2-cni"
  version    = local.linkerd_chart_version
  namespace  = kubernetes_namespace.linkerd_cni[0].metadata[0].name
  wait       = true

  values = [yamlencode({
    # GKE keeps CNI binaries in /home/kubernetes/bin, not /opt/cni/bin.
    destCNIBinDir = "/home/kubernetes/bin"
    destCNINetDir = "/etc/cni/net.d"
  })]

  depends_on = [helm_release.linkerd_crds]
}

# GoogleCASIssuer + the linkerd-identity-issuer Certificate. Rendered from a
# local chart because their CRDs do not exist until cert-manager and the CAS
# issuer are installed, which kubernetes_manifest cannot plan around.
resource "helm_release" "mesh_identity" {
  name      = "cage-mesh-identity"
  chart     = "${path.module}/charts/mesh-identity"
  namespace = kubernetes_namespace.linkerd.metadata[0].name
  wait      = true

  values = [yamlencode({
    project       = var.project_id
    location      = var.region
    caPoolId      = google_privateca_ca_pool.mesh.name
    issuerDnsName = local.identity_issuer_dns_name
    duration      = "48h0m0s"
    renewBefore   = "25h0m0s"
  })]

  depends_on = [
    helm_release.cas_issuer,
    google_privateca_certificate_authority.mesh_root,
  ]
}

resource "helm_release" "linkerd_control_plane" {
  name       = "linkerd-control-plane"
  repository = local.linkerd_repository
  chart      = "linkerd-control-plane"
  version    = local.linkerd_chart_version
  namespace  = kubernetes_namespace.linkerd.metadata[0].name
  wait       = true
  timeout    = 600

  values = [yamlencode({
    clusterDomain           = var.cluster_domain
    identityTrustDomain     = var.cluster_domain
    identityTrustAnchorsPEM = google_privateca_certificate_authority.mesh_root.pem_ca_certificates[0]
    identity = {
      # The chart still creates linkerd-identity-trust-roots from
      # identityTrustAnchorsPEM; the issuer keypair comes from the
      # cert-manager Secret instead of Helm values.
      externalCA = false
      issuer     = { scheme = "kubernetes.io/tls" }
    }
    cniEnabled = var.enable_cni
  })]

  depends_on = [
    helm_release.linkerd_crds,
    helm_release.linkerd_cni,
    helm_release.mesh_identity,
    google_compute_firewall.mesh_webhooks,
  ]
}
