from typing import Any

class NlpEngine: ...

class NlpEngineProvider:
    def __init__(self, nlp_configuration: dict[str, Any] | None = ...) -> None: ...
    def create_engine(self) -> NlpEngine: ...
