from typing import Any, Dict

class NlpEngine: ...

class NlpEngineProvider:
    def __init__(self, nlp_configuration: Dict[str, Any] | None = ...) -> None: ...
    def create_engine(self) -> NlpEngine: ...

