steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/laah-cybernetics/governance-stack/lula:0.9.5
      - -f
      - deployment/docker/Dockerfile.lula
      - .
images:
  - us-central1-docker.pkg.dev/laah-cybernetics/governance-stack/lula:0.9.5
timeout: 1200s
