# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# =============================================================================
# AUTO-GENERATED by stpa_compiler — DO NOT EDIT
# Source: config/stpa_control_structure.yaml
# Generated: 2026-09-27T16:38:53.570223+00:00
# =============================================================================
# System: CAGE Financial Advisor v1.1.0
#
# Generated Python STPA UCA rules and validator.
#
# All threshold references are resolved from the THRESHOLDS singleton
# (config/governance_thresholds.json).

from __future__ import annotations

import logging
import math
from typing import Any

from src.gateway.governance.contracts import Violation, ViolationKind
from src.gateway.governance.schemas.thresholds import THRESHOLDS
from src.gateway.governance.stpa_validator import STPAValidator, UcaRule

logger = logging.getLogger("Gateway.Governance.GeneratedSTPAValidator")


class GeneratedSTPAValidator(STPAValidator):
    """
    Auto-generated STPA validator for CAGE Financial Advisor.

    Do NOT edit this file; re-run the compiler instead:
        python -m src.gateway.governance.stpa_compiler compile
    """

    def validate(self, action_name: str, params: dict[str, Any]) -> list[Violation]:
        """Public entry-point — evaluates core STPA rules and generated UCA checks."""
        violations = list(super().validate(action_name, params))
        seen_codes = {v.code for v in violations}
        for v in self.validate_generated(action_name, params):
            if v.code not in seen_codes:
                violations.append(v)
        return violations

    def validate_generated(
        self, action_name: str, params: dict[str, Any]
    ) -> list[Violation]:
        """Run all generated UCA checks. Returns list of Violation objects."""
        violations: list[Violation] = []
        _v = self._check_uca_2(action_name, params)
        if _v:
            violations.append(_v)
        _v = self._check_uca_5(action_name, params)
        if _v:
            violations.append(_v)
        _v = self._check_uca_6(action_name, params)
        if _v:
            violations.append(_v)
        _v = self._check_uca_8(action_name, params)
        if _v:
            violations.append(_v)
        _v = self._check_uca_9(action_name, params)
        if _v:
            violations.append(_v)
        _v = self._check_uca_12(action_name, params)
        if _v:
            violations.append(_v)
        return violations

    def _check_uca_2(
        self, action_name: str, params: dict[str, Any]
    ) -> Violation | None:
        """UCA-2: Agent executes trade with stale market data (latency > threshold)."""
        try:
            if action_name != "execute_trade":
                return None
            threshold = THRESHOLDS.stpa.max_latency_ms
            val = params.get("latency_ms")
            if val is None:
                logger.warning("UCA-2: missing param `latency_ms` — failing closed.")
                return Violation(
                    tier="stpa",
                    code="STPA_UCA_UCA_2",
                    message="Missing required param `latency_ms`.",
                    kind=ViolationKind.HARD,
                )
            f_val = float(val)
            if not math.isfinite(f_val):
                return Violation(
                    tier="stpa",
                    code="STPA_UCA_UCA_2",
                    message="Non-finite param `latency_ms`.",
                    kind=ViolationKind.HARD,
                )
            if f_val > threshold:
                return Violation(
                    tier="stpa",
                    code="STPA_UCA_UCA_2",
                    message=f"Agent executes trade with stale market data (latency > threshold). ({f_val:.4f} > {threshold})",
                    kind=ViolationKind.HARD,
                )
            return None
        except Exception as exc:
            logger.error("Error evaluating UCA-2: %s", exc)
            return Violation(
                tier="stpa",
                code="STPA_UCA_UCA_2",
                message=f"Evaluation error — failing closed ({exc}).",
                kind=ViolationKind.HARD,
            )

    def _check_uca_5(
        self, action_name: str, params: dict[str, Any]
    ) -> Violation | None:
        """UCA-5: Agent executes buy order when daily drawdown exceeds limit."""
        try:
            if action_name != "execute_trade":
                return None
            threshold = THRESHOLDS.stpa.uca5_drawdown_threshold_pct
            candidates = [
                (k, params.get(k))
                for k in ("drawdown", "portfolio_drawdown_pct", "current_drawdown")
                if params.get(k) is not None
            ]
            if not candidates:
                logger.warning("UCA-5: missing param `drawdown` — failing closed.")
                return Violation(
                    tier="stpa",
                    code="STPA_UCA_UCA_5",
                    message="Missing required param `drawdown`.",
                    kind=ViolationKind.HARD,
                )
            for key_name, raw_val in candidates:
                if isinstance(raw_val, bool) or not isinstance(
                    raw_val, (int, float, str)
                ):
                    return Violation(
                        tier="stpa",
                        code="STPA_UCA_UCA_5",
                        message=f"Invalid non-numeric param `{key_name}`.",
                        kind=ViolationKind.HARD,
                    )
                f_val = float(raw_val)
                if not math.isfinite(f_val):
                    return Violation(
                        tier="stpa",
                        code="STPA_UCA_UCA_5",
                        message=f"Non-finite param `{key_name}`.",
                        kind=ViolationKind.HARD,
                    )
                eff_val = (
                    f_val * 100.0
                    if (
                        key_name
                        in (
                            "portfolio_drawdown_pct",
                            "current_drawdown",
                        )
                        and 0.0 < f_val <= 1.0
                    )
                    else f_val
                )
                if eff_val > threshold:
                    return Violation(
                        tier="stpa",
                        code="STPA_UCA_UCA_5",
                        message=f"Agent executes buy order when daily drawdown exceeds limit. ({eff_val:.4f} > {threshold})",
                        kind=ViolationKind.HARD,
                    )
            return None
        except Exception as exc:
            logger.error("Error evaluating UCA-5: %s", exc)
            return Violation(
                tier="stpa",
                code="STPA_UCA_UCA_5",
                message=f"Evaluation error — failing closed ({exc}).",
                kind=ViolationKind.HARD,
            )

    def _check_uca_6(
        self, action_name: str, params: dict[str, Any]
    ) -> Violation | None:
        """UCA-6: Agent submits market order exceeding allowable fraction of daily volume."""
        try:
            if action_name != "execute_trade":
                return None
            # Composite condition: order_size > threshold_ref(stpa.uca6_max_order_volume_fraction) * daily_vol
            lhs_val = params.get("order_size")
            rhs_val = params.get("daily_vol")
            if lhs_val is not None and rhs_val is not None:
                f_lhs = float(lhs_val)
                f_rhs = float(rhs_val)
                if (
                    f_rhs > 0
                    and f_lhs > THRESHOLDS.stpa.uca6_max_order_volume_fraction * f_rhs
                ):
                    return Violation(
                        tier="stpa",
                        code="STPA_UCA_UCA_6",
                        message="Agent submits market order exceeding allowable fraction of daily volume.",
                        kind=ViolationKind.HARD,
                    )
            return None
        except Exception as exc:
            logger.error("Error evaluating UCA-6: %s", exc)
            return Violation(
                tier="stpa",
                code="STPA_UCA_UCA_6",
                message=f"Evaluation error — failing closed ({exc}).",
                kind=ViolationKind.HARD,
            )

    def _check_uca_8(
        self, action_name: str, params: dict[str, Any]
    ) -> Violation | None:
        """UCA-8: Agent executes trade before risk assessment is complete."""
        try:
            if action_name != "execute_trade":
                return None
            if params.get("risk_assessed") is False:
                return Violation(
                    tier="stpa",
                    code="STPA_UCA_UCA_8",
                    message="Agent executes trade before risk assessment is complete.",
                    kind=ViolationKind.HARD,
                )
            return None
        except Exception as exc:
            logger.error("Error evaluating UCA-8: %s", exc)
            return Violation(
                tier="stpa",
                code="STPA_UCA_UCA_8",
                message=f"Evaluation error — failing closed ({exc}).",
                kind=ViolationKind.HARD,
            )

    def _check_uca_9(
        self, action_name: str, params: dict[str, Any]
    ) -> Violation | None:
        """UCA-9: Agent executes trade with compliance check bypassed."""
        try:
            if action_name != "execute_trade":
                return None
            if params.get("compliance_checked") is False:
                return Violation(
                    tier="stpa",
                    code="STPA_UCA_UCA_9",
                    message="Agent executes trade with compliance check bypassed.",
                    kind=ViolationKind.HARD,
                )
            return None
        except Exception as exc:
            logger.error("Error evaluating UCA-9: %s", exc)
            return Violation(
                tier="stpa",
                code="STPA_UCA_UCA_9",
                message=f"Evaluation error — failing closed ({exc}).",
                kind=ViolationKind.HARD,
            )

    def _check_uca_12(
        self, action_name: str, params: dict[str, Any]
    ) -> Violation | None:
        """UCA-12: Agent executes bounded trade when bounding contracts B1-B10 fail validation. Phase 5: execute_trade_bounded is EXTERNALLY_REVERSIBLE when B10 rollback window validation passes, enabling HITL review without confidence hard-gate per VEC-004. When B10 fails, classification override to IRREVERSIBLE_TERMINAL prevents execution."""
        try:
            if action_name != "execute_trade_bounded":
                return None
            return None
        except Exception as exc:
            logger.error("Error evaluating UCA-12: %s", exc)
            return Violation(
                tier="stpa",
                code="STPA_UCA_UCA_12",
                message=f"Evaluation error — failing closed ({exc}).",
                kind=ViolationKind.HARD,
            )


_DEFAULT_VALIDATOR = GeneratedSTPAValidator()


def _eval_uca_2(params: dict[str, Any]) -> Violation | None:
    return _DEFAULT_VALIDATOR._check_uca_2("execute_trade", params)


def _eval_uca_5(params: dict[str, Any]) -> Violation | None:
    return _DEFAULT_VALIDATOR._check_uca_5("execute_trade", params)


def _eval_uca_6(params: dict[str, Any]) -> Violation | None:
    return _DEFAULT_VALIDATOR._check_uca_6("execute_trade", params)


def _eval_uca_8(params: dict[str, Any]) -> Violation | None:
    return _DEFAULT_VALIDATOR._check_uca_8("execute_trade", params)


def _eval_uca_9(params: dict[str, Any]) -> Violation | None:
    return _DEFAULT_VALIDATOR._check_uca_9("execute_trade", params)


def _eval_uca_12(params: dict[str, Any]) -> Violation | None:
    return _DEFAULT_VALIDATOR._check_uca_12("execute_trade_bounded", params)


UCA_RULES: tuple[UcaRule, ...] = (
    UcaRule(
        uca_id="UCA-2",
        action_name="execute_trade",
        description="Agent executes trade with stale market data (latency > threshold).",
        predicate=_eval_uca_2,
    ),
    UcaRule(
        uca_id="UCA-5",
        action_name="execute_trade",
        description="Agent executes buy order when daily drawdown exceeds limit.",
        predicate=_eval_uca_5,
    ),
    UcaRule(
        uca_id="UCA-6",
        action_name="execute_trade",
        description="Agent submits market order exceeding allowable fraction of daily volume.",
        predicate=_eval_uca_6,
    ),
    UcaRule(
        uca_id="UCA-8",
        action_name="execute_trade",
        description="Agent executes trade before risk assessment is complete.",
        predicate=_eval_uca_8,
    ),
    UcaRule(
        uca_id="UCA-9",
        action_name="execute_trade",
        description="Agent executes trade with compliance check bypassed.",
        predicate=_eval_uca_9,
    ),
    UcaRule(
        uca_id="UCA-12",
        action_name="execute_trade_bounded",
        description="Agent executes bounded trade when bounding contracts B1-B10 fail validation. Phase 5: execute_trade_bounded is EXTERNALLY_REVERSIBLE when B10 rollback window validation passes, enabling HITL review without confidence hard-gate per VEC-004. When B10 fails, classification override to IRREVERSIBLE_TERMINAL prevents execution.",
        predicate=_eval_uca_12,
    ),
)

FinanceSTPAValidator = GeneratedSTPAValidator
