# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
AGP Policy Uploader (C2)
========================

Calls the Google Agent Platform API to create or update a Semantic Governance
Policy (SGP) resource using the natural language constraint text generated by
``stpa_compiler.generate_agp()``.

This module is GCP-specific and optional — operators on other platforms skip
this step. The ``gcloud beta ai semantic-governance-policies`` CLI is the
confirmed interface as of 2026-07.

The exact Python SDK method for SGP creation must be verified against
``google-cloud-aiplatform`` at implementation time; this module provides a
best-effort implementation using the REST API directly via ``google-auth``.

Usage::

    from src.gateway.governance.ingress.agp_policy_uploader import upload_agp_policy

    policy_name = upload_agp_policy(
        project="my-gcp-project",
        location="us-central1",
        policy_text_path="config/agp/generated_semantic_policy.txt",
    )
    print(f"Policy resource: {policy_name}")

Environment variables:
    GOOGLE_CLOUD_PROJECT — GCP project ID (required if not passed explicitly)
    GOOGLE_CLOUD_LOCATION — GCP region (default: us-central1)
    CAGE_AGP_POLICY_ID — existing policy ID to update (optional; creates new if absent)
"""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Any

logger = logging.getLogger("Gateway.Governance.Ingress.AGPPolicyUploader")

# Default AGP output path (mirrors stpa_compiler._DEFAULT_AGP_OUT)
_REPO_ROOT = Path(__file__).resolve().parents[4]
_DEFAULT_AGP_OUT = _REPO_ROOT / "config" / "agp" / "generated_semantic_policy.txt"

# AGP character budget (must match stpa_compiler._AGP_CHAR_BUDGET)
_AGP_CHAR_BUDGET = 5_000

# AGP API base URL (Vertex AI Agent Platform)
_AGP_API_BASE = "https://{location}-aiplatform.googleapis.com/v1beta1"


def _get_credentials() -> Any:
    """Obtain Google Cloud credentials via Application Default Credentials."""
    try:
        import google.auth
        import google.auth.transport.requests

        credentials, project = google.auth.default(
            scopes=["https://www.googleapis.com/auth/cloud-platform"]
        )
        return credentials, project
    except ImportError:
        raise RuntimeError(
            "AGPPolicyUploader: google-auth is not installed. "
            "Install it with: pip install google-auth"
        )
    except Exception as exc:
        raise RuntimeError(
            f"AGPPolicyUploader: failed to obtain Google Cloud credentials: {exc}. "
            "Ensure Application Default Credentials are configured: "
            "gcloud auth application-default login"
        ) from exc


def _validate_policy_text(policy_text: str) -> None:
    """Validate the policy text before upload."""
    if not policy_text.strip():
        raise ValueError("AGPPolicyUploader: policy text is empty.")
    if len(policy_text) > _AGP_CHAR_BUDGET:
        raise ValueError(
            f"AGPPolicyUploader: policy text exceeds {_AGP_CHAR_BUDGET}-character AGP budget "
            f"({len(policy_text)} chars). Truncate before uploading."
        )
    if "# TRUNCATED" in policy_text:
        raise ValueError(
            "AGPPolicyUploader: policy text contains TRUNCATED sentinel — "
            "the text was truncated by the compiler and cannot be uploaded as-is."
        )


def upload_agp_policy(
    policy_text: str | None = None,
    policy_text_path: str | Path | None = None,
    project: str | None = None,
    location: str | None = None,
    policy_id: str | None = None,
    display_name: str = "CAGE STPA Semantic Governance Policy",
    dry_run: bool = False,
) -> str:
    """Upload or update an AGP Semantic Governance Policy.

    Args:
        policy_text: The natural language constraint text to upload.
                     If None, reads from ``policy_text_path``.
        policy_text_path: Path to the generated policy text file.
                          Defaults to ``config/agp/generated_semantic_policy.txt``.
        project: GCP project ID. Defaults to ``GOOGLE_CLOUD_PROJECT`` env var.
        location: GCP region. Defaults to ``GOOGLE_CLOUD_LOCATION`` env var or
                  ``us-central1``.
        policy_id: Existing policy resource ID to update. If None, creates a new
                   policy. Defaults to ``CAGE_AGP_POLICY_ID`` env var.
        display_name: Human-readable display name for the policy resource.
        dry_run: If True, validates the policy text but does not call the API.

    Returns:
        The policy resource name (e.g.
        ``projects/my-project/locations/us-central1/semanticGovernancePolicies/my-policy``).

    Raises:
        ValueError: If policy text is invalid (empty, too long, or truncated).
        RuntimeError: If GCP credentials cannot be obtained or the API call fails.
    """
    # Resolve policy text
    if policy_text is None:
        effective_path = Path(policy_text_path or _DEFAULT_AGP_OUT)
        if not effective_path.exists():
            raise FileNotFoundError(
                f"AGPPolicyUploader: policy text file not found: {effective_path}. "
                "Run: python -m src.gateway.governance.stpa_compiler compile --targets agp"
            )
        policy_text = effective_path.read_text(encoding="utf-8")
        logger.info("AGPPolicyUploader: loaded policy text from %s", effective_path)

    # Validate
    _validate_policy_text(policy_text)
    char_count = len(policy_text)
    logger.info(
        "AGPPolicyUploader: policy text validated (%d/%d chars).",
        char_count,
        _AGP_CHAR_BUDGET,
    )

    # Resolve GCP config
    effective_project = project or os.environ.get("GOOGLE_CLOUD_PROJECT")
    if not effective_project:
        raise RuntimeError(
            "AGPPolicyUploader: GCP project not specified. "
            "Set GOOGLE_CLOUD_PROJECT environment variable or pass project= argument."
        )
    effective_location = location or os.environ.get("GOOGLE_CLOUD_LOCATION", "us-central1")
    effective_policy_id = policy_id or os.environ.get("CAGE_AGP_POLICY_ID")

    if dry_run:
        logger.info(
            "AGPPolicyUploader: dry-run mode — would upload %d chars to "
            "project=%s location=%s policy_id=%s",
            char_count,
            effective_project,
            effective_location,
            effective_policy_id or "(new)",
        )
        return f"projects/{effective_project}/locations/{effective_location}/semanticGovernancePolicies/dry-run"

    # Build API request
    api_base = _AGP_API_BASE.format(location=effective_location)
    parent = f"projects/{effective_project}/locations/{effective_location}"

    policy_body: dict[str, Any] = {
        "displayName": display_name,
        "constraints": policy_text,
    }

    try:
        import google.auth.transport.requests
        import requests as _requests

        credentials, _ = _get_credentials()
        auth_req = google.auth.transport.requests.Request()
        credentials.refresh(auth_req)
        headers = {
            "Authorization": f"Bearer {credentials.token}",
            "Content-Type": "application/json",
        }

        if effective_policy_id:
            # Update existing policy
            url = f"{api_base}/{parent}/semanticGovernancePolicies/{effective_policy_id}"
            response = _requests.patch(url, json=policy_body, headers=headers, timeout=30)
            operation = "updated"
        else:
            # Create new policy
            url = f"{api_base}/{parent}/semanticGovernancePolicies"
            response = _requests.post(url, json=policy_body, headers=headers, timeout=30)
            operation = "created"

        response.raise_for_status()
        result = response.json()
        resource_name = result.get("name", f"{parent}/semanticGovernancePolicies/unknown")

        logger.info(
            "AGPPolicyUploader: policy %s successfully. resource=%s",
            operation,
            resource_name,
        )
        return resource_name

    except ImportError:
        raise RuntimeError(
            "AGPPolicyUploader: 'requests' library is not installed. "
            "Install it with: pip install requests google-auth"
        )
    except Exception as exc:
        raise RuntimeError(
            f"AGPPolicyUploader: API call failed: {exc}. "
            "Verify GCP credentials and that the Agent Platform API is enabled."
        ) from exc
