from typing import Any

class RailsConfig: ...

class LLMRails:
    def __init__(self, config: Any | None = ..., **kwargs: Any) -> None: ...
    async def generate_async(self, *args: Any, **kwargs: Any) -> Any: ...
